scala:
- 2.10.4
- 2.11.2
jdk:
- oraclejdk7
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - platform-engineering@digital.cabinet-office.gov.uk
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: dBFQc9kBWWPEpEjMW26MiJdhl7xrEATSmn5oPhmmLQwTWoHY/WPrfnk5YUsfHlIlSbXXLZ6ne9ZHddJBgUZTildOkreQxsN6zbioDH8Ehe19bPoaENFmiFD/DFyOmqMQSD6l26tCEDPEaj57G2L80EmGDo6QXrnKEmQWsQ91FkY=
  - secure: A9rV5GgES2wkzPHUL3WGbhObuPsWgAJ6FYTT3PtXD3SX51qffzh87hyQbpENnbDCEP/ZSmPuI5JperQaFtReLTu9jRJRltzHWjrqvVwcQg2dqpodfscFYG7eiLB10X8I1paX460KK9Dpe2CI/qaCWFNzP0Grxls4Bx1jXMSB+Wo=
